import { ExternalLink, FolderGit2, ShieldCheck, Trophy } from "lucide-react";
import { ProfileApi } from "../types/profile.types";

export default function ProfilePortfolio({ journey }: { journey: ProfileApi["learningJourney"] }) {
  if (!journey) return null;
  const projects = journey.levels.flatMap((level) => level.tasks.map((task) => ({ ...task, level: level.levelNumber, levelTitle: level.title })));
  return <section className="rounded-2xl border border-border/70 bg-card/70 p-5 sm:p-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Verified learning portfolio</p><h2 className="mt-1 text-xl font-bold">{journey.specializationName}</h2></div><div className="flex gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary"><Trophy className="h-3.5 w-3.5" /> Level {journey.currentLevel}</span><span className="rounded-full bg-muted px-3 py-1.5 text-xs font-semibold">{journey.xp} XP</span></div></div>
    {projects.length === 0 ? <p className="mt-5 text-sm text-muted-foreground">Completed projects will appear here after the AI ownership interview verifies the student&apos;s work.</p> : <div className="mt-5 grid gap-4 sm:grid-cols-2">{projects.map((project) => <article key={project.id} className="rounded-xl border border-border bg-background/40 p-4"><div className="flex items-start justify-between gap-3"><div className="rounded-lg bg-primary/10 p-2 text-primary"><FolderGit2 className="h-4 w-4" /></div><span className="inline-flex items-center gap-1 text-[10px] font-semibold text-emerald-500"><ShieldCheck className="h-3.5 w-3.5" /> OWNERSHIP VERIFIED {project.defenseScore}%</span></div><h3 className="mt-3 font-semibold">{project.title}</h3><p className="mt-1 line-clamp-3 text-xs leading-5 text-muted-foreground">{project.description}</p><div className="mt-4 flex items-center justify-between"><span className="text-[10px] text-muted-foreground">Level {project.level} · {project.levelTitle}</span>{project.submissionUrl && <a href={project.submissionUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">View work <ExternalLink className="h-3 w-3" /></a>}</div></article>)}</div>}
  </section>;
}
