import type { Metadata } from "next";
import { Open_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Toaster } from "sonner";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Interview Coach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // suppressHydrationWarning تمنع تحذيرات التزامن الخاصة بـ next-themes
      suppressHydrationWarning
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body className={cn((openSans.className,  "min-h-full bg-background text-foreground"))}>
        <ThemeProvider attribute="class">
          <Toaster theme="dark" position="top-right" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
