import type { Metadata } from "next";
import {  Open_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { Toaster } from "sonner";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const openSans = Open_Sans({subsets:["latin"]})

export const metadata: Metadata = {
  title: "AI Interview Coach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
    >
      <body className={openSans.className}>
              <Toaster theme="dark" position="top-right"/>

        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
        {children}
        {/* <div className="absolute top-5 right-5 text-amber-700">
          <Toaster />
        </div> */}
        </ThemeProvider>
        </body>
    </html>
  );
}
