"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Check, Clipboard, Code2, KeyRound, Loader2, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { partnerService } from "./partner.service";

export default function IntegrationsPage() {
  const queryClient = useQueryClient();
  const { data: organizations = [], isLoading } = useQuery({ queryKey: ["partner-organizations"], queryFn: partnerService.organizations });
  const [name, setName] = useState("");
  const [websiteUrl, setWebsiteUrl] = useState("");
  const [newKey, setNewKey] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [selectedOrganizationId, setSelectedOrganizationId] = useState("");
  const activeOrganizationId = selectedOrganizationId || organizations[0]?.id || "";
  const { data: invitations = [] } = useQuery({ queryKey: ["partner-invitations", activeOrganizationId], queryFn: () => partnerService.invitations(activeOrganizationId), enabled: Boolean(activeOrganizationId) });
  const create = useMutation({ mutationFn: () => partnerService.create({ name, websiteUrl }), onSuccess: (data) => { setNewKey(data.apiKey); setName(""); setWebsiteUrl(""); queryClient.invalidateQueries({ queryKey: ["partner-organizations"] }); } });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(); };
  const code = `const response = await fetch("${typeof window === "undefined" ? "https://api.example.com" : window.location.origin.replace(":3000", ":5000")}/api/v1/partners/invitations", {\n  method: "POST",\n  headers: {\n    "content-type": "application/json",\n    "x-api-key": process.env.NEXWOLF_API_KEY\n  },\n  body: JSON.stringify({\n    candidateName: "Ada Student",\n    candidateEmail: "ada@example.com",\n    roleTitle: "Software Engineering Intern",\n    specialization: "Backend Engineering",\n    difficulty: "Intermediate",\n    expiresInDays: 7\n  })\n});\n\nconst { data } = await response.json();\n// Redirect or link your candidate to data.invitation.interviewUrl`;

  return <div className="space-y-7">
    <header><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary"><Code2 className="h-3.5 w-3.5" /> Partner API</div><h1 className="text-3xl font-bold">Interview candidates from your own platform</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Create a server-side API key, generate a guest interview link, and read structured AI feedback here. Candidates do not need a NexWolf account.</p></header>
    <div className="grid gap-6 lg:grid-cols-2">
      <form onSubmit={submit} className="rounded-2xl border border-border/70 bg-card/70 p-6"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><Building2 className="h-5 w-5" /></div><div><h2 className="font-bold">Create an integration</h2><p className="text-xs text-muted-foreground">The secret is displayed only once.</p></div></div><div className="space-y-3"><input required minLength={2} value={name} onChange={(event) => setName(event.target.value)} placeholder="Organization name" className="w-full rounded-xl border border-input-border bg-input px-4 py-3 text-sm outline-none focus:border-primary" /><input type="url" value={websiteUrl} onChange={(event) => setWebsiteUrl(event.target.value)} placeholder="https://yourcompany.com (optional)" className="w-full rounded-xl border border-input-border bg-input px-4 py-3 text-sm outline-none focus:border-primary" /><button disabled={create.isPending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-50">{create.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <KeyRound className="h-4 w-4" />} Generate API key</button></div></form>
      <div className="rounded-2xl border border-border/70 bg-card/70 p-6"><h2 className="font-bold">Security model</h2><div className="mt-5 space-y-4 text-sm text-muted-foreground"><p className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-500" />Keys are hashed at rest and must only be used by your server, never in browser JavaScript.</p><p className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-500" />Candidate links contain one high-entropy token, expire automatically, and can only be completed once.</p></div></div>
    </div>
    {newKey && <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-5"><p className="font-semibold text-amber-500">Copy this key now — it cannot be recovered</p><div className="mt-3 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-lg bg-background/70 px-4 py-3 text-xs">{newKey}</code><button onClick={async () => { await navigator.clipboard.writeText(newKey); setCopied(true); toast.success("API key copied"); }} className="rounded-lg border border-border bg-background px-4">{copied ? <Check className="h-4 w-4" /> : <Clipboard className="h-4 w-4" />}</button></div></div>}
    <section className="rounded-2xl border border-border/70 bg-card/70 p-6"><h2 className="font-bold">Your integrations</h2>{isLoading ? <Loader2 className="mt-5 h-5 w-5 animate-spin" /> : organizations.length === 0 ? <p className="mt-4 text-sm text-muted-foreground">No API keys created yet.</p> : <div className="mt-4 grid gap-3 sm:grid-cols-2">{organizations.map((organization) => <button onClick={() => setSelectedOrganizationId(organization.id)} key={organization.id} className={`rounded-xl border p-4 text-left ${activeOrganizationId === organization.id ? "border-primary bg-primary/5" : "border-border bg-background/40"}`}><div className="flex items-center justify-between"><p className="font-semibold">{organization.name}</p><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] font-semibold text-emerald-500">ACTIVE</span></div><p className="mt-2 font-mono text-xs text-muted-foreground">{organization.apiKeyPrefix}••••••••</p><p className="mt-2 text-xs text-muted-foreground">{organization._count.invitations} interviews created</p></button>)}</div>}</section>
    {activeOrganizationId && <section className="rounded-2xl border border-border/70 bg-card/70 p-6"><h2 className="font-bold">Candidate feedback</h2>{invitations.length === 0 ? <p className="mt-4 text-sm text-muted-foreground">Interview results will appear here after you create invitations through the API.</p> : <div className="mt-4 space-y-3">{invitations.map((invitation) => <article key={invitation.id} className="rounded-xl border border-border bg-background/40 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-semibold">{invitation.candidateName}</p><p className="text-xs text-muted-foreground">{invitation.roleTitle} · {invitation.specialization}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-muted px-2.5 py-1 text-[10px] font-semibold uppercase">{invitation.status}</span>{invitation.overallScore != null && <span className="text-lg font-bold text-primary">{invitation.overallScore}%</span>}</div></div>{invitation.feedback && <div className="mt-3 border-t border-border pt-3"><p className="text-sm text-muted-foreground">{invitation.feedback.summary}</p><p className="mt-2 text-xs font-semibold">Recommendation: {invitation.feedback.recommendation || "Review"}</p></div>}</article>)}</div>}</section>}
    <section className="rounded-2xl border border-border/70 bg-[#0d0b14] p-6 text-slate-100"><div className="mb-4 flex items-center justify-between"><div><p className="font-semibold">Create an interview link</p><p className="text-xs text-slate-400">Call this from your backend, then place the returned URL behind an Interview button.</p></div><button onClick={() => navigator.clipboard.writeText(code)} className="rounded-lg border border-white/10 p-2 text-slate-400 hover:text-white"><Clipboard className="h-4 w-4" /></button></div><pre className="overflow-x-auto text-xs leading-5 text-violet-200"><code>{code}</code></pre></section>
  </div>;
}
