import type { DifficultyLevelType } from "@/shared/types/allSkills";
import type { ProficiencyLevel } from "@/shared/types/userSkills";

export type InterviewStatusCode = "Pending" | "Running" | "Paused" | "Completed" | "Failed";
export type InterviewLanguageCode = "Arabic" | "English";

/* Report generated by the AI at the end of an interview */
export interface ReportApi {
  id: string;
  interviewId: string;
  userId: string;
  overallScore: number | string | null;
  technicalKnowledgeScore: number | string | null;
  communicationScore: number | string | null;
  confidenceScore: number | string | null;
  problemSolvingScore: number | string | null;
  currentLevel: ProficiencyLevel | null;
  recommendedNextLevel: ProficiencyLevel | null;
  strengths: string | null;
  weaknesses: string | null;
  improvementPlan: string | null;
  detailedAnalysis: Record<string, unknown> | unknown[] | null;
  recommendations: string | string[] | Record<string, unknown> | null;
  isApproved: boolean;
  isCertificateIssued: boolean;
  reportPdfUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface AnswerApi {
  id: string;
  answerText: string | null;
  score: number | string | null;
  feedback: string | null;
  isVoice: boolean;
  startedAt: string | null;
  completedAt: string | null;
}

export interface InterviewRoomQuestion {
  id: string;
  questionOrder: number;
  isAnswered: boolean;
  isSkipped: boolean;
  questionText: string | null;
  answers: AnswerApi[];
}

export interface SkillEvaluation {
  proficiencyLevel: ProficiencyLevel | null;
  aiAssessmentScore: number | string | null;
  isSelfAssessed: boolean;
  assessedByAi: boolean;
  lastAssessedAt: string | null;
}

export interface InterviewRoomSkill {
  id: string;
  name: string;
  evaluation: SkillEvaluation | null;
}

export interface InterviewRoom {
  id: string;
  difficultyLevel: DifficultyLevelType;
  status: InterviewStatusCode;
  interviewLanguage: InterviewLanguageCode;
  duration: number;
  totalQuestions: number;
  skippedQuestions: number;
  startTime: string;
  endTime: string | null;
  videoFileUrl: string | null;
  mediaExpiresAt: string | null;
  createdAt: string;
  updatedAt: string;
  report: ReportApi | null;
  questions: InterviewRoomQuestion[];
  skills: InterviewRoomSkill[];
}

/* Response envelope of GET /api/interviews/:id → data.interview */
export interface InterviewRoomResponse {
  interview: InterviewRoom;
}

/* Item shape of GET /api/interviews (list) → data.interviews[] */
export interface InterviewListItem {
  id: string;
  difficultyLevel: DifficultyLevelType;
  status: InterviewStatusCode;
  interviewLanguage: InterviewLanguageCode;
  duration: number;
  totalQuestions: number;
  skippedQuestions: number;
  startTime: string;
  endTime: string | null;
  videoFileUrl: string | null;
  mediaExpiresAt: string | null;
  createdAt: string;
  updatedAt: string;
  skills: InterviewRoomSkill[];
}

/* StartInterview response → data */
export interface StartInterviewResponse {
  interview: {
    id: string;
    difficultyLevel: DifficultyLevelType;
    interviewLanguage: InterviewLanguageCode;
    status: InterviewStatusCode;
    totalQuestions: number;
    duration: number;
    startTime: string;
    endTime: string;
    mode: "job_description" | "skills_only";
  };
  conversationId: string;
  aiConversation: {
    id: string;
    interviewId: string;
    providerConversationId: string;
    provider: string;
    model: string;
  };
  user: {
    id: string;
    firstName: string;
    lastName?: string;
    userName: string;
  };
  skills: Array<{
    id: string;
    nameAr: string;
    nameEn: string;
    difficultyLevel: DifficultyLevelType;
  }>;
}

/* GET /api/interviews/:id/questions/generate → data */
export interface GenerateQuestionResponse {
  interviewId: string;
  questionId: string;
  questionOrder: number;
  totalQuestions: number;
  question: string;
  keyTopics: string[] | null;
  interactionId: string;
  questionAudio: string | null;
}